### ISSUE TITLE
[question] backup/sync options

### ISSUE THREAD

**Issue by kverb** [dadatuputi/bitwarden_gcloud#6]
Thanks for publishing this project. Even though this was my first foray into GCP and docker, I had no issues other than getting google domains working correctly working with ddclient. I was wondering what is the best way to back up the vault or sync it to other systems (e.g. a home bitwarden server). Is there a single data file/directory than can be easily backed up somewhere? Any plans to add this functionality to this project?

**Comment by dadatuputi** [comment]
That's a good idea, and something I've thought about myself. I believe the `bitwarden` directory contains all the databases and configuration needed to restore bitwarden. I think a cron that zips it up and emails it somewhere. Do you have any ideas?

**Comment by robot9** [comment]
FYI I have set up reclone to periodically copy the data folder to Dropbox and it has been working smoothly so far

**Comment by kverb** [comment]
I probably should have more strictly separated backup vs sync in my original post. I see that google cloud has a [periodic snapshot feature](https://cloud.google.com/compute/docs/disks/scheduled-snapshots?&_ga=2.201935057.-1103438669.1606424265#create_snapshot_schedule), which is basically how we were doing local backups on the home server, although i'm not sure how secure this feature is in google cloud. My initial snapshot with just 1 vault and no attachments is about 1.2 GB. Combined with manual exports of vault data, this is probably sufficient enough for me as a backup solution. Personally, email sounds a bit clumsy; what would you do with a zipped data folder in your email? I think rsync or a dropbox solution like @robot9 mentioned is probably the most expedient. 

Syncing is more of a can of worms, partly because BW has its own concept of vault syncing between client and server db. What I was originally wondering about is syncing in the sense of replicating the server data to multiple instances, or between two totally separate systems, like a home server and google cloud, in the event google cloud becomes unavailable. @robot9 - do you use dropbox for purely backup or is the synced data folder used simultaneously in another running instance of bitwarden_rs? Trying to get hot-syncing working sounds nontrivial without also customizing the bitwarden DB code. But for me (and I suspect most users), it just needs to be warm enough to reduce the chances of a 2nd bitwarden instance serving stale vault data.

**Comment by robot9** [comment]
@kverb it’s for backup only, so the data backed up would also be encrypted. Hot-syncing seems not that easy, in the meanwhile, having the ability to run the bitwarden_rs on a virtual box from my laptop is enough for me.

**Comment by dadatuputi** [comment]
Zipping the bitwarden directory is the extend to which I would want to back it up - I haven't had any downtime issues that would necessitate syncing, however you can certainly have a warm standby by having another container mount the bitwarden directory in read only mode and syncing it to e.g. dropbox, which in turn is synced to your warm standby instance. 

I have a few hundred entries, but I don't use the file fault, and my zipped directory (omitting the icon cache and log) is 2.4MB, zipped using the command

`sudo tar -pczf backup.tar.gz --exclude bitwarden/icon_cache/ --exclude 
bitwarden/bitwarden.log bitwarden/`

With it being so small, I'm still inclined to having a e-mail solution (SMTP settings are already present for Bitwarden and fail2ban) and let people add their own cloud solution if necessary, considering how many different cloud solutions there are.

**Comment by likeasniper** [comment]
I think this solution could be integrated and would solve this problem in an elegant manner: 
Automatic daily encrypted backups to Dropbox

https://github.com/shivpatel/bitwarden_rs_dropbox_backup

I would create a PR but I still don't fully understand docker compose

**Comment by carceneaux** [comment]
I took a slightly different route here. I ended up using two different backup methods for a wholistic approach.

1. I take an application-level backup of the BitWarden DB. This eliminates the chance the backup took place while data was being written/edited which can corrupt a DB backup.
2. I then sync all files minus logs and original BW DB to object storage another public cloud provider.

I thought about submitting a PR here for this but decided there are so many ways to do this (as shown by previous comments) I would refrain. I will share my `docker-compose.yml` config in case anyone is interested.

```yml
db-backup:
    # Application-level backup of SQLite
    image: bruceforce/bw_backup
    restart: always
    container_name: db-backup
    depends_on:
    - bitwarden
    volumes:
    - ${PWD}/bitwarden:/data/
    - /etc/timezone:/etc/timezone:ro
    - /etc/localtime:/etc/localtime:ro
    - ${PWD}/:/backup_folder/
    environment:
    - 'CRON_TIME=0 */4 * * *' # backup is performed every 4 hours
    - DB_FILE=/data/db.sqlite3
    - BACKUP_FILE=/backup_folder/backups/backup.sqlite3
    - BACKUP_FILE_PERMISSIONS=755
    - TIMESTAMP=true
    - DELETE_AFTER=7
    - UID=0
    - TZ

file-backup:
    # File-level backup to an AWS S3 Bucket
    image: istepanov/backup-to-s3
    restart: always
    container_name: file-backup
    volumes:
    - ${PWD}/:/data:ro
    environment:
    - 'CRON_SCHEDULE=15 */4 * * *' # backup is performed every 4 hours
    - ACCESS_KEY
    - SECRET_KEY
    - S3_PATH=s3://${S3_BUCKET}/
    - PARAMS="--no-delete-removed --exclude db.sqlite3* --exclude fail2ban.sqlite3 --exclude *.log"
```

My current BitWarden DB size is 1.4MB. Even estimating a 2MB size puts my monthly egress for backups ~360MB which includes DB backups every four hours.

@dadatuputi If you'd like a PR to incorporate any of this in the project, let me know and I'll make it happen.
